table Fact_Performance_Reviews
	lineageTag: e64f31cb-729f-4373-af6b-9999b0896447

	column ReviewID
		dataType: string
		lineageTag: dccf281f-fef4-4ee2-986d-388d64146b98
		summarizeBy: none
		sourceColumn: ReviewID

		annotation SummarizationSetBy = Automatic

	column EmployeeID
		dataType: string
		lineageTag: 81aaa72f-f256-43e2-9a7e-112ba56e1810
		summarizeBy: none
		sourceColumn: EmployeeID

		annotation SummarizationSetBy = Automatic

	column ReviewDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 37c1a9cd-3f1c-4f43-9f11-8de973e60c56
		summarizeBy: none
		sourceColumn: ReviewDate

		variation Variation
			isDefault
			relationship: 2be492ff-ea1a-4988-9231-9f08a1c65c8c
			defaultHierarchy: LocalDateTable_7cc0f696-0009-494e-abe0-4eb2f10ba2da.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ReviewPeriod
		dataType: string
		lineageTag: e08494b8-d0ab-48ee-bc63-bebef17159f0
		summarizeBy: none
		sourceColumn: ReviewPeriod

		annotation SummarizationSetBy = Automatic

	column PerformanceRating
		dataType: double
		lineageTag: ba36031a-ca09-429b-8da3-23c3594e9255
		summarizeBy: sum
		sourceColumn: PerformanceRating

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SalesAchieved_Or_TicketsClosed
		dataType: int64
		formatString: 0
		lineageTag: 0e1cdf5e-ab12-4ca4-92f5-29754999bb84
		summarizeBy: sum
		sourceColumn: SalesAchieved_Or_TicketsClosed

		annotation SummarizationSetBy = Automatic

	partition Fact_Performance_Reviews = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("D:\DPBA\DPBA First Project\Fact_Performance_Reviews.xlsx"), null, true),
				    Fact_Performance_Reviews_Sheet = Source{[Item="Fact_Performance_Reviews",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Fact_Performance_Reviews_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"ReviewID", type text}, {"EmployeeID", type text}, {"ReviewDate", type date}, {"ReviewPeriod", type text}, {"PerformanceRating", type number}, {"SalesAchieved_Or_TicketsClosed", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

